# Base configs
baseurl: "https://okosh.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Oleg Koshkarov"
subtitle: "See the world through my eyes!"
author: "Oleg Koshkarov"
header:
 title: "Photography"
 subtitle: "by Oleg Koshkarov"
footer:
 name: "Hey there, my name is Oleg"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/okosh/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
   github: "https://www.github.com/okosh"
